movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movieapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')


    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from . forms import MovieForm


# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie= Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name = request.POST.get("name",)
        desc = request.POST.get("desc", )
        year = request.POST.get("year", )
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()

    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<div class="d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card p-4 shadow" style="width: 100%; max-width: 500px; border-radius: 15px;">
        <h3 class="card-title text-center mb-4">Add a New Movie</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group mb-3">
                <label for="name" class="form-label">Movie Name</label>
                <input type="text" class="form-control rounded-pill" id="name" name="name" placeholder="Enter movie name"  required>
            </div>

            <div class="form-group mb-3">
                <label for="desc" class="form-label">Movie Description</label>
                <textarea class="form-control rounded-3" id="desc" name="desc" placeholder="Enter movie description" rows="3" class="pad" required></textarea>
            </div>

            <div class="form-group mb-3">
                <label for="year" class="form-label">Release Year</label>
                <input type="text" class="form-control rounded-pill" id="year" name="year" placeholder="Enter release year" required>
            </div>

            <div class="form-group mb-3">
                <label for="img" class="form-label">Movie Poster</label>
                <input type="file" class="form-control rounded-pill" id="img" name="img">
            </div>

            <button type="submit" class="btn btn  rounded-pill w-100 mt-3"  style="background-color:#2980b9;">Submit</button>
<!--            <div><a href="/" style="text-decoration:none;padding-left:200px;">Home</a></div>-->
        </form>
    </div>
</div>
{% endblock %}

movieproject/templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
<body>

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      ONLINE MOVIE STORE
  </a>
<a class="btn btn-warning" href="/">Home</a>
     <a class="btn btn-warning" href="/add">Add</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  Are you sure ! Do you want to delete this movie???
  <input type="submit">
</form>

movieproject/templates/detail.html
{%extends 'base.html'%}
{% block body %}

<br>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="200">
        </div>

<div class="col-m">
    <h2>{{movie.name}}</h2>
    <h4>{{movie.desc}}</h4>
    <h6>{{movie.year}}</h6>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
</div>


            </div>
</div>
{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

movieproject/templates/index.html
{%extends 'base.html'%}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="margin-top:20px;">
  <img src="{{i.img.url}}" class="card-img-top" src="..." alt="Card image cap" width="200px" height="200px;">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{%url 'movieapp:detail' i.id %}" class="btn btn-primary">Open</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}